name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.repository_owner != github.event.pull_request.head.repo.owner.login }}

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
      - name: Set up JDK 1.8
        uses: actions/setup-java@8db439b6b47e5e12312bf036760bbaa6893481ac # renovate: tag=v2.3.1
        with:
          java-version: 8
          distribution: 'adopt'

      - uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B -Dchangelist=-${{github.run_number}} clean verify

      - name: Extract version
        run: |
          VERSION=$(cat pom.xml | grep '<revision' | grep -o -E '[0-9]+\.[0-9]+(\.[0-9]+)?')
          echo "${VERSION}-${{github.run_number}}" > target/version.txt

      - name: Upload plugin
        uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2.2.4
        with:
          name: jobcacher
          path: |
            target/jobcacher.hpi
            target/version.txt

  release:
    needs: [build]

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Setup Git user
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Download plugin
        uses: actions/download-artifact@3be87be14a055c47b01d3bd88f8fe02320a9bb60 # renovate: tag=v2.0.10
        with:
          name: jobcacher
          path: .

      - name: Create git tag
        run: |
          v=$(cat version.txt)
          git tag v$v
          git push origin v$v
          echo "VERSION=${v}" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # renovate: tag=v1
        with:
          files: jobcacher.hpi
          name: ${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          body: Relase v${{ env.VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
